site_name: firescript
repo_url: https://github.com/alec-jensen/firescript
repo_name: alec-jensen/firescript
docs_dir: docs
site_dir: site
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
# GitHub Pages deployment configuration
deploy:
  provider: github
  branch: gh-pages
nav:
  - Home: README.md
  - Language Specification: language_specification.md
  - Types & Variables: variables.md
  - Arrays: arrays.md
  - Control Flow: control_flow.md
  - Functions & Methods: functions.md
  - Classes & Inheritance: classes.md
  - Scoping Rules: scoping.md
  - Type System: type_system.md
  - Changelog: changelog.md
markdown_extensions:
  - toc:
      permalink: True