from enum import Enum, auto


class NodeTypes(Enum):
    ROOT = "Root"
    IF_STATEMENT = "IfStatement"
    ELIF_STATEMENT = "ElifStatement"
    ELSE_STATEMENT = "ElseStatement"
    WHILE_STATEMENT = "WhileStatement"
    BREAK_STATEMENT = "BreakStatement"
    CONTINUE_STATEMENT = "ContinueStatement"
    VARIABLE_DECLARATION = "VariableDeclaration"
    VARIABLE_ASSIGNMENT = "VariableAssignment"
    BINARY_EXPRESSION = "BinaryExpression"
    EQUALITY_EXPRESSION = "EqualityExpression"
    RELATIONAL_EXPRESSION = "RelationalExpression"
    LITERAL = "Literal"
    IDENTIFIER = "Identifier"
    FUNCTION_CALL = "FunctionCall"
    SCOPE = "Scope"
    ARRAY_LITERAL = "ArrayLiteral"
    ARRAY_ACCESS = "ArrayAccess"
    METHOD_CALL = "MethodCall"
    COMPOUND_ASSIGNMENT = "CompoundAssignment"
    UNARY_EXPRESSION = "UnaryExpression"
    FUNCTION_DEFINITION = "FunctionDefinition"
    PARAMETER = "Parameter"
    RETURN_STATEMENT = "ReturnStatement"
